<?php
$parentPath = "views/layout.phtml";
?>
<div class="container">
    <form action="<?=$getActionUrl("Book", "AddPost")?>" method="post" class="col-lg-6 mx-auto needs-validation" novalidate>
        <div class="col-12 p-0 mb-2">
            <a class="return" href="<?=$returnUrl?>">
                <img class="icon-sm" src="img/flaticon/back.svg" alt="<">
                <span style="color: #4180ab !important;">Zpět</span>
            </a>
        </div>
        <h2>Přidat knihu</h2>
        <?php
            if(!empty($errors)){
                foreach($errors as $error){
                    echo("<div class='alert alert-danger' role='alert'>$error</div>");
                }
            }
        ?>
        <div class="form-row">
            <div class="form-group col-md-8">
                <label for="name">Název knihy</label>
                <input type="text" class="form-control" name="name" id="name" placeholder="Název knihy" required>
            </div>
            <div class="form-group col-md-4">
                <label for="genreId">Žánr</label>
                <div class="input-group">
                    <select class="custom-select" id="genreId" name="genreId" required>
                        <option selected value="">Vyberte žánr</option>
                        <?php foreach($genres as $genre): ?>
                        <option value="<?=$genre->getId()?>"><?=$genre->getGenre()?></option>
                        <?php endforeach ?>
                    </select>
                    <div class="input-group-append">
                        <a href="<?=$getActionUrl("Genre", "Add", ["returnUrl" => $getActionUrl("Book", "Add")])?>" class="btn btn-outline-success">+</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-md-6">
                <label for="authorId">Autor</label>
                <div class="input-group">
                    <select class="custom-select" id="authorId" name="authorId" required>
                        <option selected value="">Vyberte autora</option>
                        <?php foreach($authors as $author): ?>
                        <option value="<?=$author->getId()?>"><?=$author->getFullname()?></option>
                        <?php endforeach ?>
                    </select>
                    <div class="input-group-append">
                        <a href="<?=$getActionUrl("Author", "Add", ["returnUrl" => $getActionUrl("Book", "Add")])?>" class="btn btn-outline-success">+</a>
                    </div>
                </div>
            </div>
            <div class="form-group col-md-6">
                <label for="isbn">ISBN</label>
                <input type="text" class="form-control" name="isbn" id="isbn" placeholder="ISBN" pattern="(?:(?=.{17}$)97[89][ -](?:[0-9]+[ -]){2}[0-9]+[ -][0-9]|97[89][0-9]{10}|(?=.{13}$)(?:[0-9]+[ -]){2}[0-9]+[ -][0-9Xx]|[0-9]{9}[0-9Xx])" required>
                <div class="valid-feedback">
                    ISBN je ve správném formátu.
                </div>
                <div class="invalid-feedback">
                    ISBN musí být ve správném formátu.
                </div>
            </div>
        </div>
        <div class="form-group">
            <label for="description">Popis</label>
            <textarea class="form-control" id="description" name="description" rows="3"></textarea>
        </div>
        <div class="form-row">
            <div class="form-group col-md-3">
                <label for="pageCount">Počet stran</label>
                <input type="number" class="form-control" id="pageCount" name="pageCount" min="1" required>
            </div>
            <div class="form-group col-md-3">
                <label for="year">Rok vydání</label>
                <input type="number" class="form-control" id="year" name="year" max="<?=date("Y")?>" required>
            </div>
            <div class="form-group col-md-6">
                <label for="conditionId">Kondice</label>
                <select class="custom-select" id="conditionId" name="conditionId" required>
                    <option selected value="">Vyberte kondici</option>
                    <?php foreach($conditions as $condition): ?>
                        <option value="<?=$condition->getId()?>"><?=$condition->getCondition()?></option>
                    <?php endforeach ?>
                </select>
            </div>
        </div>
        <div class="form-group">
            <label for="placeId">Budova</label>
            <select class="custom-select" id="placeId" name="placeId" required>
                <option selected value="">Vyberte budovu</option>
                <?php foreach($places as $place): ?>
                <option value="<?=$place->getId()?>"><?=$place->getPlace()?></option>
                <?php endforeach ?>
            </select>
        </div>
        <div class="form-group">
            <div class="custom-control custom-checkbox">
                <input type="checkbox" class="custom-control-input" name="maturita" id="maturita" value="TRUE">
                <label class="custom-control-label" for="maturita">Je v maturitním seznamu</label>
            </div>
        </div>
        <button type="submit" class="btn btn-primary mx-auto d-block">Přidat</button>
    </form>
    <script>
    (function() {
    'use strict';
    window.addEventListener('load', function() {
        // Fetch all the forms we want to apply custom Bootstrap validation styles to
        var forms = document.getElementsByClassName('needs-validation');
        // Loop over them and prevent submission
        var validation = Array.prototype.filter.call(forms, function(form) {
        form.addEventListener('submit', function(event) {
            if (form.checkValidity() === false) {
            event.preventDefault();
            event.stopPropagation();
            }
            form.classList.add('was-validated');
        }, false);
        });
    }, false);
    })();
</script>
</div>