<?php
$parentPath = "views/layout.phtml";
?>
<div class="col-xs-12 col-lg-10 mx-auto">
    <div class="row">
        <div class="col-md-2 p-0 mb-2">
            <a class="return" href="<?=$returnUrl?>">
                <img class="icon-sm" src="img/flaticon/back.svg" alt="<">
                <span style="color: #4180ab !important;">Zpět</span>
            </a>
        </div>
        <h2 class="text-center col-md-6">Půjčení knih</h2>
    </div>
    <table class="table">
        <thead>
            <tr>
                <th>ID knihy</th>
                <th>Název knihy</th>
                <th>Autor</th>
                <th>Umístění</th>
                <th>Žadatel</th>
                <th>Akce</th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($bookRequests as $bookRequest): ?>
            <tr>
                <td><?=$bookRequest->getBookId()?></td>
                <td><?=$bookRequest->getBookName()?></td>
                <td><?=$bookRequest->getBookAuthorName()?></td>
                <td><?=$bookRequest->getPlaceName()?></td>
                <td><?=$bookRequest->getUserName()?></td>
                <td class="p-2">
                    <a href='<?=$getActionUrl("Book", "BorrowPost", ["id" => $bookRequest->getId(), "act" => "accept", "returnUrl" => $getActionUrl("Book", "Borrow")])?>' tabindex="-1" class="px-1">
                        <img class="icon" src="img/flaticon/tick.svg" alt="Detail" title="Přejít na detail">
                    </a>
                    <a href='<?=$getActionUrl("Book", "BorrowPost", ["id" => $bookRequest->getId(), "act" => "decline", "returnUrl" => $getActionUrl("Book", "Borrow")])?>' tabindex="-1" class="px-1">
                        <img class="icon" src="img/flaticon/cross.svg" alt="Upravit" title="Upravit parametry">
                    </a>
                </td>
            </tr>
        <?php endforeach ?>
        </tbody>
    </table>
</div>