<?php
$parentPath = "views/layout.phtml";
?>
<div class="col-xs-12 col-lg-10 mx-auto">
    <div class="row mb-3">
        <div class="col-md-2 p-0">
            <a class="return" href="<?=$returnUrl?>">
                <img class="icon-sm" src="img/flaticon/back.svg" alt="<">
                <span style="color: #4180ab !important;">Zpět</span>
            </a>
        </div>
        <h2 class="text-center col-md-6">Vypůjčené knihy</h2>
        <?php
            if(!empty($errors)){
                foreach($errors as $error){
                    echo("<div class='alert alert-danger' role='alert'>$error</div>");
                }
            }
        ?>
    </div>
    <table class="table">
        <thead>
            <tr>
                <th>ID knihy</th>
                <th>Název knihy</th>
                <th>Autor</th>
                <th>Umístění</th>
                <th>Žadatel</th>
                <th>Vypůjčeno</th>
                <th>Akce</th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($bookRequests as $bookRequest): ?>
            <tr>
                <td><?=$bookRequest->getBookId()?></td>
                <td><?=$bookRequest->getBookName()?></td>
                <td><?=$bookRequest->getBookAuthorName()?></td>
                <td><?=$bookRequest->getPlaceName()?></td>
                <td><?=$bookRequest->getUserName()?></td>
                <td><?=($bookRequest->getBookBorrowed()) ? $bookRequest->getBookBorrowed()->format('d. m. Y H:i') : ""?></td>
                <td class="p-2">
                    <a href='<?=$getActionUrl("Book", "ReturnPost", ["id" => $bookRequest->getId(), "returnUrl" => $getActionUrl("Book", "Return")])?>' tabindex="-1" class="px-1">
                        <img class="icon" src="img/flaticon/tick.svg" alt="Detail" title="Vrátit knihu">
                    </a>
                </td>
            </tr>
        <?php endforeach ?>
        </tbody>
    </table>
</div>