<footer>
    <address class="last">Font generated by <a href="http://www.flaticon.com">flaticon.com</a>. Under <a href="http://creativecommons.org/licenses/by/3.0/">CC, Designed by</a>:
        <a data-file="005-imac" href="http://www.flaticon.com/authors/smashicons">Smashicons</a>
    <address class="last">Fonts by: <a href="http://fontsquirrel.com/">Fontsquirrel.com</a>.</address>
    <address class="last">&copy; 2018</address>
</footer>

<?php
    if(isset($db)) $db->close();
?>