<?php
$parentPath = "views/layout.phtml";
?>
<div id="button-box">
	<a href="pujcit.html"><button class="blue">Pùjèit knihu</button></a>
	<a href="vratit.html"><button class="blue">Vrátit knihu</button></a>
	<a href="seznam.html"><button class="blue">Seznam knih</button></a>
	<a href="pujcene.html"><button class="blue">Zarezervované knihy</button></a>
	<a href="pridat.html"><button class="blue">Pøidat knihu</button></a>
</div>