<?php
$parentPath = "views/layout.phtml";
?>
<div class="card-columns justify-content-center px-3 px-lg-5">
		<div class="card">
			<img src="img/flaticon/searchbooks.svg" class="card-img-top px-3 pt-3" alt="">
			<div class="card-body">
				<a href="<?=$getActionUrl("Book", "Index", [
					"page" => 0,
					"search" => "",
					"returnUrl" => $getActionUrl("Home", "Index")
					])?>" class="btn btn-light stretched-link">Seznam knih</a>
			</div>
		</div>
		<div class="card">
			<img src="img/flaticon/borrowbook.svg" class="card-img-top px-3 pt-3" alt="">
			<div class="card-body">
				<a href="<?=$getActionUrl("Book", "Requests", ["returnUrl" => $getActionUrl("Home", "Index")])?>" class="btn btn-light stretched-link">Půjčit knihu</a>
			</div>
		</div>
		<div class="card">
			<img src="img/flaticon/reservedbooks.svg" class="card-img-top px-3 pt-3" alt="">
			<div class="card-body">
				<a href="<?=$getActionUrl("Book", "Reservations", ["returnUrl" => $getActionUrl("Home", "Index")])?>" class="btn btn-light stretched-link">Zarezervované knihy</a>
			</div>
		</div>
		<div class="card">
			<img src="img/flaticon/returnbook.svg" class="card-img-top px-3 pt-3" alt="">
			<div class="card-body">
				<a href="<?=$getActionUrl("Book", "Return", ["returnUrl" => $getActionUrl("Home", "Index")])?>" class="btn btn-light stretched-link">Vrátit knihu</a>
			</div>
		</div>
		<div class="card">
			<img src="img/flaticon/addbook.svg" class="card-img-top px-3 pt-3" alt="">
			<div class="card-body">
				<a href="<?=$getActionUrl("Book", "Add",[
                "returnUrl" => $getActionUrl("Home", "Index")
                ])?>" class="btn btn-light stretched-link">Přidat knihu</a>
			</div>
		</div>
	</div>
</div>