<?php
$parentPath = "views/layout.phtml";
?>
<?php
$parentPath = "views/layout.phtml";
?>
<div class="container">
    <form action="<?=$getActionUrl("Genre", "AddPost")?>" method="post" class="col-lg-6 mx-auto needs-validation" novalidate>
        <h2>Přidat žánr</h2>
        <?php
            if(!empty($errors)){
                foreach($errors as $error){
                    echo("<div class='alert alert-danger' role='alert'>$error</div>");
                }
            }
        ?>
        <div class="form-group">
            <label for="name">Název žánru</label>
            <input type="text" class="form-control" name="_genre" id="genre" placeholder="Název žánru" required>
        </div>
        <button type="submit" class="btn btn-primary mx-auto d-block">Přidat</button>
    </form>
    <script>
    (function() {
    'use strict';
    window.addEventListener('load', function() {
        // Fetch all the forms we want to apply custom Bootstrap validation styles to
        var forms = document.getElementsByClassName('needs-validation');
        // Loop over them and prevent submission
        var validation = Array.prototype.filter.call(forms, function(form) {
        form.addEventListener('submit', function(event) {
            if (form.checkValidity() === false) {
            event.preventDefault();
            event.stopPropagation();
            }
            form.classList.add('was-validated');
        }, false);
        });
    }, false);
    })();
</script>
</div>