<?php
$parentPath = "views/layout.phtml";
?>
<div class="container" style="text-align:center">
    <div class="card mx-auto" style="max-width: 24rem; text-align:center">
        <div id="qr-code"></div>
        <div class="card-body">
            <h5 class="card-title">Kniha přidána</h5>
            <p class="card-text">Vytiskněte QR kód a nalepte na knihu.</p>
            <a href="javascript:printBookQR('qr-code', <?=$book->getId()?>, '<?=$book->getName()?>');" class="btn btn-primary">Tisk</a>
            <a href='<?=$getActionUrl("Book", "Detail", ["id" => $book->getId()])?>' tabindex="-1" class="btn btn-secondary px-1">Přejít na detail</a>
        </div>
    </div>
    <script>
        $(document).ready(function() {
            renderBookQR("qr-code", <?=$book->getId()?>);
        });
    </script>
</div>