<?php
$parentPath = "views/layout.phtml";
?>
<div class="container">
    <div class="row">
        <div class="col-md-6 p-3">
            <div class="col-12">
                <h2><?=$book->getName()?></h2>
                <h3><?=$book->getAuthorName()?></h3>
            </div>
            <div class="col-12">
                <?php if($book->getBorrowedByName() != ""):?>
                    <img class="icon" src="img/flaticon/cross.svg" alt="" style="height: 2rem;" title="Zapůjčené">
                    <span><?=$book->getBorrowedByName()?></span>
                <?php else:?>
                    <img class="icon" src="img/flaticon/tick.svg" alt="" style="height: 2rem;" title="Dostupné">
                    <span>Dostupné</span>
                <?php endif?>
            </div>
        </div>
        <div class="col-md-6">
            <table class="table">
                <tbody>
                    <tr>
                        <td>Žánr</td>
                        <td><?php
                            if($book->getISBN() == "")
                                echo "Není uvedeno.";
                            else
                                echo $book->getGenreName();
                            ?>
                        </td>
                    </tr>
                    <tr>
                        <td>ISBN</td>
                        <td><?php
                            if($book->getISBN() == "")
                                echo "Není uvedeno.";
                            else
                                echo $book->getISBN();
                            ?>
                        </td>
                    </tr>
                    <tr>
                        <td>Rok vydání</td>
                        <td><?=$book->getYear()?></td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>