<?php
$parentPath = "views/layout.phtml";
?>
<script src="http://jecas.cz/files/qr/qrcode.min.js"></script>
<div class="container">
    <div class="row">
        <div class="col-xs-12 col-lg-6 pb-3">
            <div class="col-12">
                <h2><?=$book->getName()." "?><?php
                    if($book->getMaturitaReady() == 1)
                        echo '<span class="badge badge-success">Maturita</span>';
                ?></h2>
                <h3><?=$book->getAuthorName()?></h3>
            </div>
            <div class="col-12">
                <?php if($book->getBorrowedByName() != ""):?>
                    <img class="icon" src="img/flaticon/cross.svg" alt="" style="height: 2rem;" title="Zapůjčené">
                    <span><?=$book->getBorrowedByName()?></span>
                <?php else:?>
                    <img class="icon" src="img/flaticon/tick.svg" alt="" style="height: 2rem;" title="Dostupné">
                    <span>Dostupné</span>
                <?php endif?>
            </div>
            <div class="col-12">
            <?=$book->getDescription()?>
            </div>
            <div class="col-12 pt-3">
                <div id="qr-code"></div>
            </div>
        </div>
        <div class="col-xs-12 col-lg-6">
            <table class="table">
                <tbody>
                    <tr>
                        <td>Žánr</td>
                        <td><?php
                            if($book->getGenreName() == "")
                                echo "Není uvedeno.";
                            else
                                echo $book->getGenreName();
                            ?>
                        </td>
                    </tr>
                    <tr>
                        <td>ISBN</td>
                        <td><?php
                            if($book->getISBN() == "")
                                echo "Není uvedeno.";
                            else
                                echo $book->getISBN();
                            ?>
                        </td>
                    </tr>
                    <tr>
                        <td>Rok vydání</td>
                        <td><?=$book->getYear()?></td>
                    </tr>
                    <tr>
                        <td>Počet stran</td>
                        <td><?=$book->getPageCount()?></td>
                    </tr>
                    <tr>
                        <td>Kondice</td>
                        <td><?php
                            if($book->getConditionName() == "")
                                echo "Není uvedeno.";
                            else
                                echo $book->getConditionName();
                            ?>
                        </td>
                    </tr>
                    <tr>
                        <td>Budova</td>
                        <td><?php
                            if($book->getPlaceName() == "")
                                echo "Není uvedeno.";
                            else
                                echo $book->getPlaceName();
                            ?>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
    <script>
    var qrcode = new QRCode("qr-code", {
        text: window.location.protocol + window.location.hostname + "/?id=" + <?php echo $book->getId()?> + "&controller=Book&action=Detail",
        colorDark : "#000000",
        colorLight : "#ffffff",
        correctLevel : QRCode.CorrectLevel.H
    });
    </script>
</div>