<?php
$parentPath = "views/layout.phtml";
$books = iterator_to_array($books);
$pagesCount = ceil($bookCount/20);
?>
<div class="col-xs-12 col-lg-10 mx-auto">
    <div class="row">
        <h2 class="text-center col-md-6">Seznam knih</h2>
        <form class="form-inline my-2 my-lg-0 col-md-6" method="post" action="<?=$getActionUrl("Book", "Index")?>">
            <input class="hidden" type="hidden" name="page" value="0">
            <input class="form-control mr-sm-2" name="search" type="search" placeholder="Čapek" aria-label="Hledat" value="<?=$search?>">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Hledat</button>
        </form>
    </div>
    <table class="table">
        <thead>
            <tr>
                <th>Název</th>
                <th>ISBN</th>
                <th>Autor</th>
                <th>Rok vydání</td>
                <th>Dostupnost</th>
                <th>Detail</th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($books as $book): ?>
            <tr>
                <td><?=$book->getName()?></td>
                <td><?=$book->getIsbn()?></td>
                <td><?=$book->getAuthorName()?></td>
                <td><?=$book->getYear()?></td>
                <?php if($book->getBorrowedByName() != ""):?>
                    <td class="p-2">
                        <img src="img/flaticon/cross.svg" alt="" style="height: 2rem;">
                        <span><?=$book->getBorrowedByName()?></span>
                    </td>
                <?php else:?>
                    <td class="p-2">
                        <img src="img/flaticon/tick.svg" alt="" style="height: 2rem;">
                    </td>
                <?php endif?>
                <td class="p-2">
                    <a href='<?=$getActionUrl("Book", "Detail", ["id" => $book->getId()])?>' tabindex="-1">
                        <img src="img/flaticon/search.svg" alt="Detail" style="height: 2rem;">
                    </a>
                </td>
            </tr>
        <?php endforeach ?>
        </tbody>
    </table>
    <nav aria-label="Page navigation example">
    <ul class="pagination justify-content-end">
        <li class='page-item <?php if($page < 1) echo "disabled"?>'>
        <a class="page-link" href='<?=$getActionUrl("Book", "Index", ["page" => ($page - 1), "search" => ""])?>' tabindex="-1">Previous</a>
        </li>
        <?php
        for($i = 0; $i < $pagesCount; $i++)
        {
            if($i == $page)
                $active = "active";
            else
                $active = "";
            echo("<li class='page-item $active'><a class='page-link' href='".$getActionUrl("Book", "Index", ["page" => $i, "search" => ""])."'>".($i + 1)."</a></li>");
        }
        ?>
        <li class='page-item  <?php if($page == $pagesCount - 1) echo "disabled"?>'>
        <a class="page-link" href='<?=$getActionUrl("Book", "Index", ["page" => ($page + 1), "search" => ""])?>'>Next</a>
        </li>
    </ul>
    </nav>
</div>