<?php
$parentPath = "views/layout.phtml";
?>

<?php if(isset($errors)): ?>
    <?php foreach ($errors as $error): ?>
       <div>
           <?=$error?>
       </div>
    <?php endforeach ?>
<?php endif; ?>

<form action="<?=$getActionUrl("Article", "update")?>" method="post">
    <input type="hidden" name="id" value="<?=$id?>">
    <input type="text" name="title" value="<?=$title?>" placeholder="Title">
    <input type="text" name="content" value="<?=$content?>" placeholder="Content">
    <input type="submit" value="Update">
</form>