<?php
$parentPath = "views/layout.phtml";
?>

<?php if(isset($errors)): ?>
    <?php foreach ($errors as $error): ?>
       <div>
           <?=$error?>
       </div>
    <?php endforeach ?>
<?php endif; ?>

<form action="<?=$getActionUrl("Account", "register")?>" method="post">
    <input type="text" name="name" placeholder="Name" value="<?=$name ?? ""?>">
    <input type="password" name="password" placeholder="Password" value="<?=$password ?? ""?>">
    <input type="password" name="passwordCheck" placeholder="Password check" value="<?=$passwordCheck ?? ""?>">
    <input type="submit" value="Register">
</form>