<?php
$userAuthenticationService = $provideDependency("\authentication\UserAuthenticationServiceInterface");

$isLogged = $userAuthenticationService->isLogged();
$loggedUserName = $isLogged ? $userAuthenticationService->getLoggedUserName() : null;
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Knihovna SPŠ Trutnov</title>
    <link rel="stylesheet" href="css/style.css">
</head>
<body>
    <header>
       <h1 id="logo"> <img src="./obrazky/logo.jpg" alt="Logo SPŠ Trutnov" width="35px" height="35px"> SPŠ Trutnov Knihovna</h1>
    </header>
    <main>
        <?=$child?>
    </main>
	<footer>
		<div> &copy; 2019 </div>
	</footer>
</body>
</html>