<?php
$parentPath = "views/layout.phtml";
?>

<?php if ($loggedUserId !== null): ?>
    <a href="<?=$getActionUrl("Article", "create")?>">Create</a>
<?php endif; ?>

<?php foreach ($articlesWithAuthor as $articleWithAuthor): ?>
   <article>
       <header>
           <h2><?=$articleWithAuthor->getArticle()->getTitle()?></h2>
       </header>
       <main>
           <p><?=$articleWithAuthor->getArticle()->getContent()?></p>
       </main>
       <footer>
           Author: <?=$articleWithAuthor->getAuthor()->getName()?>
           <?php if ($loggedUserId === $articleWithAuthor->getArticle()->getAuthorId()): ?>
               <a href="<?=$getActionUrl("Article", "update", ["id" => $articleWithAuthor->getArticle()->getId()])?>">Update</a>
               <a href="<?=$getActionUrl("Article", "delete", ["id" => $articleWithAuthor->getArticle()->getId()])?>">Delete</a>
           <?php endif; ?>
       </footer>
   </article>
<?php endforeach ?>