<?php
$parentPath = "views/layout.phtml";
?>
<div class="container">
    <form action="<?=$getActionUrl("Author", "AddPost")?>" method="post" class="col-lg-6 mx-auto needs-validation" novalidate>
        <div class="col-12 p-0 mb-2">
            <a class="return" href="<?=$returnUrl?>">
                <img class="icon-sm" src="img/flaticon/back.svg" alt="<">
                <span style="color: #4180ab !important;">Zpět</span>
            </a>
        </div>
        <h2>Přidat autora</h2>
        <div class="form-group">
            <label for="name">Jméno</label>
            <input type="text" class="form-control" name="_firstname" id="firstname" placeholder="Jméno" required>
        </div>
        <div class="form-group">
            <label for="name">Příjmení</label>
            <input type="text" class="form-control" name="_lastname" id="lastname" placeholder="Příjmení" required>
        </div>
        <button type="submit" class="btn btn-primary mx-auto d-block">Přidat</button>
    </form>
    <script>
    (function() {
    'use strict';
    window.addEventListener('load', function() {
        // Fetch all the forms we want to apply custom Bootstrap validation styles to
        var forms = document.getElementsByClassName('needs-validation');
        // Loop over them and prevent submission
        var validation = Array.prototype.filter.call(forms, function(form) {
        form.addEventListener('submit', function(event) {
            if (form.checkValidity() === false) {
            event.preventDefault();
            event.stopPropagation();
            }
            form.classList.add('was-validated');
        }, false);
        });
    }, false);
    })();
</script>
</div>