<?php
$parentPath = "views/layout.phtml";
?>

<?php if(isset($errors)): ?>
    <?php foreach ($errors as $error): ?>
       <div>
           <?=$error?>
       </div>
    <?php endforeach ?>
<?php endif; ?>

<form action="<?=$getActionUrl("Article", "create")?>" method="post">
    <input type="text" name="title" placeholder="Title" value="<?=$title ?? ""?>">
    <input type="text" name="content" placeholder="Content" value="<?=$content ?? ""?>">
    <input type="submit" value="Create">
</form>